# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=320)),
                ('brand', models.CharField(blank=True, max_length=320)),
                ('contract', models.CharField(max_length=320)),
                ('invoice_period', models.CharField(default='Annual', max_length=320)),
                ('start', models.DateField(default=datetime.date(2017, 9, 13))),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product or Service', max_length=320)),
                ('description', models.TextField(default='N/A')),
                ('comment', models.TextField(blank=True)),
                ('quantity', models.CharField(default='1', max_length=320)),
                ('finyear', models.IntegerField(choices=[('2015', '2015/16'), ('2016', '2016/17'), ('2017', '2017/18'), ('2018', '2018/19'), ('2019', '2019/20')])),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('predicted_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrooge.ContractReference')),
            ],
        ),
    ]
