# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 04:55
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=320)),
                ('brand', models.CharField(default='N/A', max_length=320)),
                ('contract', models.CharField(default='N/A', max_length=320)),
                ('invoice_period', models.CharField(default='Annual', max_length=320)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product or Service', max_length=320)),
                ('description', models.TextField(default='N/A')),
                ('comment', models.TextField(blank=True, default='')),
                ('quantity', models.CharField(default='1', max_length=320)),
                ('finyear', models.IntegerField(choices=[(2015, '2015/16'), (2016, '2016/17'), (2017, '2017/18'), (2018, '2018/19'), (2019, '2019/20')])),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('predicted_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allocated_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrooge.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='CostBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('description', models.TextField(blank=True)),
                ('service_pool', models.CharField(choices=[('Internal Labor', 'Internal Labor'), ('External Labor', 'External Labor'), ('Outside Services', 'Outside Services'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Facilities and Power', 'Facilities and Power'), ('Telecom', 'Telecom'), ('Other', 'Other'), ('Internal Services', 'Internal Services')], max_length=64)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrooge.Cost')),
            ],
        ),
        migrations.CreateModel(
            name='ITSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=320)),
                ('cost_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('user_count', models.PositiveIntegerField()),
                ('cost_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='it_systems',
            field=models.ManyToManyField(blank=True, editable=False, to='scrooge.ITSystem'),
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='scrooge.UserGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set([('vendor', 'contract')]),
        ),
        migrations.AlterUniqueTogether(
            name='costbreakdown',
            unique_together=set([('cost', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='cost',
            unique_together=set([('name', 'finyear', 'contract')]),
        ),
    ]
