# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrooge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractreference',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cost',
            name='finyear',
            field=models.IntegerField(choices=[(2015, '2015/16'), (2016, '2016/17'), (2017, '2017/18'), (2018, '2018/19'), (2019, '2019/20')]),
        ),
        migrations.AlterUniqueTogether(
            name='contractreference',
            unique_together=set([('vendor', 'contract')]),
        ),
    ]
