# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrooge', '0002_auto_20170915_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='brand',
            field=models.CharField(default='N/A', max_length=320),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract',
            field=models.CharField(default='N/A', max_length=320),
        ),
    ]
