# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrooge', '0002_auto_20170919_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costbreakdown',
            options={'ordering': ('-percentage',)},
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='total_user_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='user_groups',
            field=models.ManyToManyField(blank=True, default=4, to='scrooge.UserGroup'),
        ),
    ]
