# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 06:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrooge', '0002_auto_20170913_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('description', models.TextField(blank=True)),
                ('service_pool', models.CharField(choices=[('Internal Labor', 'Internal Labor'), ('External Labor', 'External Labor'), ('Outside Services', 'Outside Services'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Facilities and Power', 'Facilities and Power'), ('Telecom', 'Telecom'), ('Other', 'Other'), ('Internal Services', 'Internal Services')], max_length=64)),
                ('percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='ITSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=320)),
                ('cost_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('user_count', models.PositiveIntegerField()),
                ('cost_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='cost',
            name='allocated_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrooge.Cost'),
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='it_systems',
            field=models.ManyToManyField(to='scrooge.ITSystem'),
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='user_groups',
            field=models.ManyToManyField(to='scrooge.UserGroup'),
        ),
    ]
