# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrooge', '0003_auto_20170914_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystem',
            name='cost_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='system_id',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='cost_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='cost',
            unique_together=set([('name', 'finyear', 'contract')]),
        ),
    ]
