# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 16:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import scrooge.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrooge', '0003_auto_20170919_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ('-user_count',)},
        ),
        migrations.AddField(
            model_name='usergroup',
            name='cost_centres',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='it_systems',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costbreakdown',
            name='user_groups',
            field=models.ManyToManyField(blank=True, default=scrooge.models.largest_user_group, to='scrooge.UserGroup'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='cost_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='cost_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
