# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrooge', '0004_auto_20170914_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='predicted_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
