# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrooge', '0004_auto_20171009_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scrooge.UserGroup'),
            preserve_default=False,
        ),
    ]
