# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrooge', '0006_auto_20171009_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbreakdown',
            name='system_cost',
            field=models.BooleanField(default=False),
        ),
    ]
