# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 23:58
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product or Service', max_length=320)),
                ('description', models.TextField(default='N/A')),
                ('comment', models.TextField(blank=True, default='')),
                ('quantity', models.CharField(default='1', max_length=320)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allocated', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-cost_estimate',),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('vendor', models.CharField(max_length=320)),
                ('brand', models.CharField(default='N/A', max_length=320)),
                ('reference', models.CharField(default='N/A', max_length=320)),
                ('invoice_period', models.CharField(default='Annual', max_length=320)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-cost_estimate',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('name', models.CharField(max_length=320)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ('-percentage',),
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('name', models.CharField(max_length=320)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('cc_count', models.PositiveIntegerField(default=0)),
                ('system_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ('-cost_estimate',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndUserService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('name', models.CharField(max_length=320)),
                ('total_user_count', models.PositiveIntegerField(default=0, editable=False)),
                ('divisions', models.ManyToManyField(to='recoup.Division')),
            ],
            options={
                'ordering': ('-cost_estimate',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'ordering': ('end',),
            },
        ),
        migrations.CreateModel(
            name='ITSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('system_id', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=320)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.Division')),
            ],
            options={
                'ordering': ('-cost_estimate',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('name', models.CharField(max_length=320)),
                ('system_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'IT Platform',
                'ordering': ('-cost_estimate',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('name', models.CharField(editable=False, max_length=320, unique=True)),
            ],
            options={
                'ordering': ('-cost_estimate',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('weighting', models.FloatField(default=1)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.Platform')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.ITSystem')),
            ],
        ),
        migrations.CreateModel(
            name='EndUserCost',
            fields=[
                ('cost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recoup.Cost')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.EndUserService')),
            ],
            options={
                'ordering': ('-cost_estimate',),
                'abstract': False,
            },
            bases=('recoup.cost',),
        ),
        migrations.CreateModel(
            name='ITPlatformCost',
            fields=[
                ('cost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recoup.Cost')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.Platform')),
            ],
            options={
                'ordering': ('-cost_estimate',),
                'abstract': False,
            },
            bases=('recoup.cost',),
        ),
        migrations.AddField(
            model_name='cost',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='recoup.Bill'),
        ),
        migrations.AddField(
            model_name='cost',
            name='service_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='recoup.ServicePool'),
        ),
        migrations.AddField(
            model_name='bill',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.Contract'),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.FinancialYear'),
        ),
        migrations.AlterUniqueTogether(
            name='systemdependency',
            unique_together=set([('system', 'platform')]),
        ),
    ]
