# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product or Service', max_length=320)),
                ('description', models.TextField(default='N/A')),
                ('comment', models.TextField(blank=True, default='')),
                ('quantity', models.CharField(default='1', max_length=320)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=320)),
                ('brand', models.CharField(default='N/A', max_length=320)),
                ('reference', models.CharField(default='N/A', max_length=320)),
                ('invoice_period', models.CharField(default='Annual', max_length=320)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('user_count', models.PositiveIntegerField()),
                ('cc_count', models.PositiveIntegerField()),
                ('system_count', models.PositiveIntegerField(editable=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ITSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=320)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.Division')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.Division')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.Contract'),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.FinancialYear'),
        ),
    ]
