# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoup', '0003_itsystem_cost_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='depends_on',
            field=models.ManyToManyField(through='recoup.SystemDependency', to='recoup.Platform'),
        ),
    ]
