# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoup', '0004_itsystem_depends_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('vendor',)},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='endusercost',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='enduserservice',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='itplatformcost',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='itsystem',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ('name',), 'verbose_name': 'IT Platform'},
        ),
        migrations.AlterModelOptions(
            name='servicepool',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='cost_estimate',
        ),
        migrations.RemoveField(
            model_name='division',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='division',
            name='cost_estimate',
        ),
        migrations.RemoveField(
            model_name='enduserservice',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='enduserservice',
            name='cost_estimate',
        ),
        migrations.RemoveField(
            model_name='enduserservice',
            name='total_user_count',
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='financialyear',
            name='cost_estimate',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='cost_estimate',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='cost_estimate',
        ),
        migrations.RemoveField(
            model_name='servicepool',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='servicepool',
            name='cost_estimate',
        ),
        migrations.RemoveField(
            model_name='systemdependency',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='systemdependency',
            name='cost_estimate',
        ),
    ]
