# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recoup', '0005_auto_20171108_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('user_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='division',
            name='cc_count',
        ),
        migrations.RemoveField(
            model_name='division',
            name='system_count',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='system_count',
        ),
        migrations.AddField(
            model_name='costcentre',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoup.Division'),
        ),
    ]
