# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoup', '0006_auto_20171212_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcentre',
            options={'ordering': ('-division__user_count', '-user_count')},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('-user_count',)},
        ),
        migrations.AlterModelOptions(
            name='itsystem',
            options={'ordering': ('cost_centre_name', 'name')},
        ),
        migrations.RenameField(
            model_name='itsystem',
            old_name='cost_centre',
            new_name='cost_centre_name',
        ),
    ]
