# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recoup', '0007_auto_20180116_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recoup.CostCentre'),
        ),
    ]
