# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoup', '0008_itsystem_cost_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='position',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
