# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoup', '0009_division_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='itsystem',
            options={'ordering': ('cost_centre__name', 'name')},
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='cost_centre_name',
        ),
        migrations.AlterField(
            model_name='division',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
